server:
  port: 9003

spring:
  application:
    name: shortify
    version: 09.02.24
    description: An internet service to shorten URLs and maintain its statistic
  jpa:
    showSql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/shortify-url-db
    username: sa
    password:
    driverClassName: org.h2.Driver
  sql:
    init:
      mode: always
